services:
  # local build test
  # app:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   ports:
  #     - "8080:4000"
  #   depends_on:
  #     - postgres
  #   environment:
  #     SECRET_KEY_BASE: lmGy2/Mxu10pQYoMKqFGejS2B7a4vfWy/Kr5Uumo5s54BdQLg9yE3wZD5dgzfnOP
  #     DATABASE_URL: postgresql://postgres:postgres@postgres:5432/vmemo_prod
  #     PHX_HOST: app.vmemo.orb.local
  #     PORT: 8080
  #   env_file:
  #     - .env

  postgres:
    image: postgres:16
    restart: on-failure
    hostname: postgres
    ports:
      - "54321:5432"
    volumes:
      - ./_data/pg-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: vmemo_dev

  typesense:
    image: typesense/typesense:27.1
    restart: on-failure
    hostname: typesense
    ports:
      - "8765:8108"
    volumes:
      - ./_data/ts-data:/data
    command: "--data-dir /data --api-key=xyz --enable-cors"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8765/health"]
      interval: 30s
      timeout: 10s
      retries: 5
