name: Publish Docker Image

on:
  push:
    tags:
      - "*"
    branches:
      - dev
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: thaddeusjiang
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: thaddeusjiang/vmemo:${{ github.ref_name }}

        # main branch is :latest
      - name: Publish :latest image
        if: github.ref == 'refs/heads/main'
        uses: docker/build-push-action@v3
        with:
          context: .
          push: true
          tags: thaddeusjiang/vmemo:latest

      - name: Log out from Docker Hub
        run: docker logout
